# Generated by Django 3.0.4 on 2020-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_auto_20200316_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='preguntas',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
