# Generated by Django 3.0.4 on 2020-03-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_examen_preguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='respuestas',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
