# Generated by Django 3.0.4 on 2020-03-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_examen_respuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='opcional',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
